### ISSUE TITLE
Add shortcut to flip through the tabs on a PR

### ISSUE THREAD

**Issue by gholtslander-va** [Yatser/prettypullrequests#16]
It would be cool to just be able to hit the Tilde key and have it flip through each of the tabs on a pull request. An example of this is how you can go command-\` to flip through windows in an app on OS X. 

After a PR is loaded, pressing \` would take you to the Commits tab. Pressing it again would take you to Files. Pressing it a third time would take you back to the first page, Conversation. I should be able to keep hitting ` to cycle through all of the tabs.

I don't know how easy this is. But it would be pretty awesome.

**Comment by gholts** [comment]
Pretty demanding guy
