### ISSUE TITLE
Add the Chrome Extension store link to the repository somewhere

### ISSUE THREAD

**Issue by gholts** [Yatser/prettypullrequests#25]
Currently people just have to Google for the extension if they want to use it after finding it on GitHub. Or they have to manually run it, I guess. But it'd be cool to be able to just share them this repo link so that they can contribute if they want, but they could then also get right to the download page from here. Which is this:

https://chrome.google.com/webstore/detail/pretty-pull-requests-gith/ljnjpkadhhcdniohpfilddnhahoigdec?hl=en

I'd do it, but I don't have permissions to do so.

**Comment by Yatser** [comment]
Alright, I copy pasted your link and added it to the readme lol

**Comment by gholts** [comment]
Beauty.

**Comment by gholts** [comment]
Though I was thinking as well, you can edit the description and add a webpage for the repo, you should do that too.

**Comment by Yatser** [comment]
You mean on the chrome webstore description, to the repo? I already have that in both the description text and the website link...

**Comment by gholts** [comment]
Um, it's something that should go here:

![image](https://cloud.githubusercontent.com/assets/8973794/8361164/a9b15b3c-1b2e-11e5-97c1-a2954b518ff8.png)

Like this:

![image](https://cloud.githubusercontent.com/assets/8973794/8361174/bddae65a-1b2e-11e5-9973-857d9a2642f3.png)
![image](https://cloud.githubusercontent.com/assets/8973794/8361178/c52afab2-1b2e-11e5-8d52-e762cbbdb1ca.png)

**Comment by gholts** [comment]
I'll leave it up to you. Maybe it's weird to have a really long link up there. Maybe we could (in a distant future) setup a pretty url that just redirects to the Chrome extension store instead.
