### ISSUE TITLE
Keep in local storage currently collapsed files

### ISSUE THREAD

**Issue by bnetter** [Yatser/prettypullrequests#32]
So we could close and reopen the tab and the files would still be collapsed.

**Comment by jguepin** [comment]
:+1:

**Comment by tmosmant** [comment]
:+1:

**Comment by Yatser** [comment]
I like it guys, I've been wanting that feature for a long time. There would also have to be a feature in the dropdown to really quickly clear that state if you didn't want them stored.

Is this something you will submit a PR for or something you would like me to look into developing? I haven't had a ton of time lately so I haven't been super responsive to these issues, but I can probably find time to do this.

**Comment by Yatser** [comment]
Hey guys,

Exciting news, this has FINALLY just been released! It will roll out slowly because publishing can take up to an hour.

I am sorry it took so long after merging to push it up, I just wanted to test it a little bit.

Thanks for your hard work @tmosmant @bnetter!
