### ISSUE TITLE
Change the logo

### ISSUE THREAD

**Issue by Yatser** [Yatser/prettypullrequests#34]
Github has (very nicely) asked me to change the logos of this extension, since I am in violation of their logo policies here https://github.com/logos. Need to come up with a new logo/icon that makes sense for this extension while not being recognizable as an official github product.

**Comment by tmosmant** [comment]
I emailed the GitHub support and the [`octigon-git-pull-request`](https://octicons.github.com/icon/git-pull-request/) icon can be used for a logo or within a browser extension. This can be a temporary replacement.

**Comment by Yatser** [comment]
Hi @tmosmant, I have some designers working on a new logo that will probably just be a one-off of something cute (originally I thought it should be some kind of collapse icon, but, nothing about the title of the extension says the features are limited to just that, so it should be feature-agnostic). I don't need to change it in the interim, just soon, thanks for the input!

**Comment by tmosmant** [comment]
That sounds good!

**Comment by Yatser** [comment]
The new logo is now released! Check it out:
![128x128](https://cloud.githubusercontent.com/assets/1159120/11788172/471069d8-a255-11e5-864d-a2adcd0f1431.png)
