### ISSUE TITLE
Diffs for files collapse if you've ever collapsed them before

### ISSUE THREAD

**Issue by gholtslander-va** [Yatser/prettypullrequests#35]
I think most people (certainly @Yatser ) know of this bug, but just making it to make it official and to make it known I plan to work on this.

Reproduction:
1. Open a pull request 
2. Collapse a diff for a file
3. Make another pull request
4. See that the diff for that file is still collapsed, even though it's a new pull request

My current thought is to make the key somewhat more specific than it is now. Currently we're just storing a diff id which you'd think would be enough, but it seems to be the same diff id between PRs. Perhaps storing a concatenation of `projectName + '|' + pullRequestNumber + '|' + diffId`, which dang well better be unique enough.

**Comment by tmosmant** [comment]
My bad, I thought this ID was uniq. Storing the concatenation seems to be a good solution here.

**Comment by gholtslander-va** [comment]
This got fixed a while back in #37 I believe
