### ISSUE TITLE
PR categories for large PRs with many files

### ISSUE THREAD

**Issue by benprime** [Yatser/prettypullrequests#56]
In my organization, we have many very large pull requests that we do formal code review meetings on.

I would like the ability to define categories in the scope of a single PR and add files to these categories. A list (tree?) of these categories could be displayed on the lefthand side of the page. I would like to then add changed files (or even specific hunks) to a category. In this way, I would be able to prepare for a code review meeting by creating categories like 'core changes', 'necessary refactors', 'tests', 'changes that need a group decision', etc. And organize my categories in the order they will be presented at the meeting.

I have not yet seen any chrome extension that allow for this kind of thing. Any suggestions to alternative ways of solving this problem would also be welcome.

**Comment by ghost** [comment]
Hi @bsmith-sw,

It's not something I would be looking to solve with this chrome extension. The features you are describing sound to me like a lot of features I've used in full blown code review tools... something of which it would be very hard to replicate in a github chrome extension. I suggest you look into code review tools that integrate with github.

Thanks for your interest!
